name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2.4.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.4.0
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
    - run: yarn build --if-present
    - run: yarn test

    - name: Codacy Analysis CLI
      uses: codacy/codacy-analysis-cli-action@4.0.0
